#!/bin/bash

# SSL 证书管理脚本
# 提供便捷的证书管理命令

set -e

NGINX_CONF_DIR="/etc/nginx/conf.d"

# 显示帮助信息
show_help() {
    cat << EOF
SSL Certificate Manager - Usage:

Commands:
  create <domain> <email> [proxy_pass]  - Create certificate + nginx config
  renew                                  - Renew all certificates
  renew-force                            - Force renew all certificates
  list                                   - List all certificates
  delete <domain>                        - Delete a certificate and its nginx config
  info <domain>                          - Show certificate information
  test                                   - Test certificate renewal (dry-run)

Examples:
  cert create example.com admin@example.com
  cert create example.com admin@example.com http://backend:8080
  cert renew
  cert list
  cert info example.com

EOF
}

# 生成域名 nginx 配置文件（含 SSL）
generate_nginx_conf() {
    local domain=$1
    local proxy_pass=$2
    local conf_file="$NGINX_CONF_DIR/${domain}.conf"

    # 根据是否有 proxy_pass 决定 location 内容
    if [ -n "$proxy_pass" ]; then
        local location_block="        proxy_pass $proxy_pass;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;"
    else
        local location_block="        root /var/www/html;
        index index.html;"
    fi

    cat > "$conf_file" << EOF
# Auto-generated by cert create - $(date '+%Y-%m-%d %H:%M:%S')
# Domain: $domain

server {
    listen 80;
    listen [::]:80;
    server_name $domain;

    # Let's Encrypt webroot 验证
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        try_files \$uri =404;
    }

    # HTTP 重定向到 HTTPS
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $domain;

    # SSL 证书
    ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;

    # 阻止 PHP 文件执行
    location ~ \.php$ {
        return 444;
    }

    location / {
$location_block
    }
}
EOF

    echo "Nginx config generated: $conf_file"
}

# 创建新证书
create_cert() {
    local domain=$1
    local email=$2
    local proxy_pass=$3

    if [ -z "$domain" ] || [ -z "$email" ]; then
        echo "Error: Domain and email are required"
        echo "Usage: cert create <domain> <email> [proxy_pass]"
        exit 1
    fi

    echo "Creating certificate for $domain..."
    certbot certonly \
        --webroot \
        --webroot-path=/var/www/html \
        --email "$email" \
        --agree-tos \
        --no-eff-email \
        -d "$domain"

    echo "Generating nginx config for $domain..."
    generate_nginx_conf "$domain" "$proxy_pass"

    echo "Testing nginx configuration..."
    nginx -t

    echo "Reloading nginx..."
    nginx -s reload

    echo "Done. Certificate and nginx config created for $domain"
}

# 续期所有证书
renew_certs() {
    echo "Renewing all certificates..."
    certbot renew --webroot --webroot-path=/var/www/html
    echo "Reloading nginx..."
    nginx -s reload
}

# 强制续期所有证书
force_renew_certs() {
    echo "Force renewing all certificates..."
    certbot renew --force-renewal --webroot --webroot-path=/var/www/html
    echo "Reloading nginx..."
    nginx -s reload
}

# 列出所有证书
list_certs() {
    certbot certificates
}

# 删除证书及其 nginx 配置
delete_cert() {
    local domain=$1

    if [ -z "$domain" ]; then
        echo "Error: Domain is required"
        echo "Usage: cert delete <domain>"
        exit 1
    fi

    echo "Deleting certificate for $domain..."
    certbot delete --cert-name "$domain"

    local conf_file="$NGINX_CONF_DIR/${domain}.conf"
    if [ -f "$conf_file" ]; then
        rm -f "$conf_file"
        echo "Removed nginx config: $conf_file"
        nginx -s reload
    fi
}

# 显示证书信息
show_cert_info() {
    local domain=$1

    if [ -z "$domain" ]; then
        echo "Error: Domain is required"
        echo "Usage: cert info <domain>"
        exit 1
    fi

    certbot certificates --cert-name "$domain"

    if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
        echo ""
        echo "Certificate validity:"
        openssl x509 -in "/etc/letsencrypt/live/$domain/fullchain.pem" -text -noout | grep -A 2 "Validity"
    fi
}

# 测试续期（dry-run）
test_renew() {
    echo "Testing certificate renewal (dry-run)..."
    certbot renew --dry-run --webroot --webroot-path=/var/www/html
}

# 主逻辑
case "$1" in
    create)
        create_cert "$2" "$3" "$4"
        ;;
    renew)
        renew_certs
        ;;
    renew-force)
        force_renew_certs
        ;;
    list)
        list_certs
        ;;
    delete)
        delete_cert "$2"
        ;;
    info)
        show_cert_info "$2"
        ;;
    test)
        test_renew
        ;;
    help|--help|-h|"")
        show_help
        ;;
    *)
        echo "Unknown command: $1"
        echo ""
        show_help
        exit 1
        ;;
esac
